name = "geocoding-api"
main = "worker/src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
dir = "worker"

[vars]
ES_INDEX_PREFIX = "geo_"
DEFAULT_LANG = "es"

[env.production.vars]
ES_INDEX_PREFIX = "geo_"
DEFAULT_LANG = "es"

# To set secrets for production (using Basic Auth):
# wrangler secret put ES_URL --env production
# wrangler secret put ES_USERNAME --env production
# wrangler secret put ES_PASSWORD --env production
